### ISSUE TITLE
Payment gateway: Radio button of the Parent Guardian section is not working. It currently set to both ticked.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Academic-Group#149]
![image](https://cloud.githubusercontent.com/assets/11186313/16439371/3415e5ac-3dea-11e6-8971-ed0c83e6b0dd.png)

**Comment by jsemblantetitanweb** [comment]
This is not a bug. It is currently set to both ticked because they are two different radio buttons that connects to the others form below. Ticking the Not required checkbox on the form below and ticket the other "use as primary billing address" would uncheck the first radio button above. Same behavior as the "use as primary contact".
