### ISSUE TITLE
Payment gateway: There is no left padding when page is resized to lower resolution.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Academic-Group#151]
![image](https://cloud.githubusercontent.com/assets/11186313/16440026/8ff48670-3df0-11e6-8e2a-8b9267dccbd7.png)
![image](https://cloud.githubusercontent.com/assets/11186313/16440069/e25dfe46-3df0-11e6-9fea-79ee9e06e909.png)

**Comment by jsemblantetitanweb** [comment]
About this issue. The issue is too hard to replicate. It appears rarely on the site as I resize it. Sometimes it appears on some viewports after inputting the exact viewport value and when I refresh it again or resize it to bigger or smaller viewport and goes back again to where the issue is recently found, the issue is again not visible. I also tested it on the actual mobile devices and the issue can't be found.

**Comment by roseliesromeo** [comment]
Issue no longer exist in common resolutions.
